### ISSUE TITLE
Class hierarchy not updated after move

### ISSUE THREAD

**Issue by tudorache** [who-icatx/icatx-project#224]
This happened with icfeditor on WHOFIC Beta:

- I moved "Skin related structure test 6" under "Skin related structure test 5"
- As a result, the moved class was shown both in the old place and the new place

See screenshot below.

**This does not happen if I do it with my user name (that has manager privileges).**

<img width="1364" alt="Image" src="https://github.com/user-attachments/assets/c63e5ca0-b9bc-4458-a29f-aa8ec7e09a58" />

**Comment by matthewhorridge** [comment]
This was fixed in PR: https://github.com/protegeproject/webprotege-backend-service/pull/125

Not sure why this was never merged.  @alexsilaghi please can you take a look at merging this?  It'a a pretty critical fix for various hierarchy issues.

CC @csnyulas 

FYI you will need to approve https://github.com/protegeproject/webprotege-gwt-ui/pull/213 to see everything working because PR 213 fixes an error due to a EntityNode.statuses missing on the client.

**Comment by alexsilaghi** [comment]
it was merged

**Comment by csnyulas** [comment]
Closing this, as there was a fix provided for it, and since the fix we haven't seen this happening again.

**Comment by csnyulas** [comment]
I am reopening this as it still occurs sometimes. 

Most recently I encountered it while testing the solution provided for the issue [Error while changing parents #325](https://github.com/who-icatx/icatx-project/issues/325). When I removed two subclasses of the ["ICF Extension Code" class (in the "WHOFIC Foundation 2025.09.25 (TESTING)" project)](https://icd.who.int/icatx/#projects/bd87a181-05b8-4fe2-a0a0-87bb63864d10/perspectives/cfcddc69-1edc-429d-817f-1a707d90152d?selection=Class(%3Chttp://id.who.int/icd/entity/152976210%3E)), namely ["Anatomical localization"](https://icd.who.int/icatx/#projects/bd87a181-05b8-4fe2-a0a0-87bb63864d10/perspectives/df6a1b1b-587a-4bef-ba85-a4371986b12d?selection=Class(%3Chttp://id.who.int/icd/entity/437219407%3E)) and ["Anatomy and Topograhy"](https://icd.who.int/icatx/#projects/bd87a181-05b8-4fe2-a0a0-87bb63864d10/perspectives/df6a1b1b-587a-4bef-ba85-a4371986b12d?selection=Class(%3Chttp://id.who.int/icd/entity/1154280071%3E)), after the first operation, the class hierarchy did not update (neither did the content of the "Parents" view or the "Project Feed"). After the second operation, however, all the views were updated properly.

**Comment by csnyulas** [comment]
@alexsilaghi do you think that the fixes described in https://github.com/who-icatx/icatx-project/issues/296#issuecomment-3557408444, address this issue as well? Can we close this? Is there a way to test it?

**Comment by alexsilaghi** [comment]
tested. created classes and move them around. it seems that the fix with websocket solved this one as well. 

<img width="1528" height="307" alt="Image" src="https://github.com/user-attachments/assets/12c2642e-8d45-401d-a983-684e9ee2eab9" />
