### ISSUE TITLE
Fix problems with Consciousness Postcoordination Scale Values

### ISSUE THREAD

**Issue by csnyulas** [who-icatx/icatx-project#324]
The GCS Eye Score scale values were not properly migrated to iCAT-X. They do not appear for the two entites that have them set in iCAT:

```
http://id.who.int/icd/entity/1328725971      (Coma)
http://id.who.int/icd/entity/1305388531      (Glasgow Coma Scale, eyes opening)
```
Also the 
- "Has GSC Score" should not appear in the list of consciousness post-coordination axes, as it itself has sub-axes (note that it has a typo as well)
- Rename "**Has GSC** Verbal Score" in "**GCS** Verbal Score" (there is both a typo and an extra "Has ")

<img width="1516" height="899" alt="Image" src="https://github.com/user-attachments/assets/18261bfa-134c-4ca5-9bc3-f94ffcb489f1" />

**Comment by alexsilaghi** [comment]
fixed in https://github.com/who-icatx/webprotege-postcoordination-service/commit/076e9ed391d22e7cd58bcf2cb5d5eb0d66090957.

**Comment by csnyulas** [comment]
The main issues of not showing the values, and displaying wrong labels have been corrected, indeed. The only thing that has left is that the "GCS Score" still appears. This being a relatively minor problem, I am moving this issue to a later milestone.

**Comment by alexsilaghi** [comment]
It was a configuration issue. I've simply removed it from PostCoordinationTableConfiguration

**Comment by csnyulas** [comment]
Where did you fix the configuration? In the WHOFIC Production project I still see it:

<img width="1522" height="976" alt="Image" src="https://github.com/user-attachments/assets/f5cfff47-3d51-4310-b3eb-812f6ae5ff54" />

Do you (or I) need to reset something for the change to take effect on my end?

**Comment by alexsilaghi** [comment]
<img width="1385" height="836" alt="Image" src="https://github.com/user-attachments/assets/73759e59-a5f5-4b73-afbc-68a9b8381a52" /> the postcoordination service had to be restarted since we cache this config.

**Comment by csnyulas** [comment]
Excellent. Thanks, @alexsilaghi , it is working now. Closing this.
